default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch("DB_PASSWORD") { '' } %>
  host: <%= ENV.fetch("DB_HOST") { '127.0.0.1' } %>
  timeout: 5000

development:
  <<: *default
  database: db_user

test:
  <<: *default
  database: db_teste